# Generated by Django 5.0.4 on 2025-02-10 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_testdbworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('description_text', models.JSONField(blank=True, null=True, verbose_name='Project Description RT')),
                ('network', models.PositiveSmallIntegerField(choices=[(0, 'Secret'), (2, 'Public')], default=2)),
                ('identifier', models.CharField(max_length=12, verbose_name='Project Identifier')),
                ('emoji', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_prop', models.JSONField(null=True)),
                ('module_view', models.BooleanField(default=True)),
                ('cycle_view', models.BooleanField(default=True)),
                ('issue_views_view', models.BooleanField(default=True)),
                ('page_view', models.BooleanField(default=True)),
                ('inbox_view', models.BooleanField(default=False)),
                ('cover_image', models.URLField(blank=True, max_length=800, null=True)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_assignee', to=settings.AUTH_USER_MODEL)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_lead', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_project', to='db.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('projectbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.projectbasemodel')),
                ('name', models.CharField(max_length=255, verbose_name='State Name')),
                ('description', models.TextField(blank=True, verbose_name='State Description')),
                ('color', models.CharField(max_length=255, verbose_name='State Color')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('sequence', models.FloatField(default=65535)),
                ('group', models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='backlog', max_length=20)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('db.projectbasemodel',),
        ),
        migrations.AddField(
            model_name='projectbasemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='projectbasemodel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('projectbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.projectbasemodel')),
                ('comment', models.TextField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (10, 'Viewer'), (5, 'Guest')], default=10)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('db.projectbasemodel',),
        ),
        migrations.AddField(
            model_name='project',
            name='default_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_state', to='db.state'),
        ),
    ]
