# Generated by Django 5.0.4 on 2025-03-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_projectbasemodel_project_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
    ]
