# Generated by Django 5.0.4 on 2025-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_name_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
