# Generated by Django 5.0.4 on 2025-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, default=1, upload_to='workspace/'),
            preserve_default=False,
        ),
    ]
