# Generated by Django 5.0.4 on 2025-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_workspace_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(max_length=800, null=True, upload_to='project/'),
        ),
    ]
