
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth.hashers import make_password
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import default_token_generator
from django.conf import settings
from db.models import User
from api.utils import send_otp


# -----------------------------------------------------------------
# Frontend base URL — adjust this to match your Next.js dev/prod URL
# -----------------------------------------------------------------
FRONTEND_BASE_URL = getattr(settings, "FRONTEND_BASE_URL", "http://localhost:3000")


class ForgotPasswordEndpoint(APIView):
    """
    Author: [Your Name] on April 18, 2025
    Purpose: Accepts an email address and, if a matching user exists,
             sends a password-reset link to that email.
    Input parameters: email
    Return: { message, statusCode }

    Security note: Always returns 200 so attackers cannot enumerate accounts.
    The reset link contains a uid (base64-encoded user pk) and a one-time
    token generated by Django's built-in PasswordResetTokenGenerator.
    """

    def post(self, request):
        email = request.data.get("email", "").strip()

        if not email:
            return Response({"message": "Email is required.", "statusCode": 400})

        try:
            user = User.objects.get(email=email)

            # Build a safe, one-use token
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)

            # Construct the frontend reset URL that includes uid & token as query params
            reset_url = f"{FRONTEND_BASE_URL}/reset-password?uid={uid}&token={token}"

            send_otp(
                email_subject="Reset Your CS Pro Plane Password",
                email_template="password_reset.html",
                recipient_email=user.email,
                context={
                    "reset_url": reset_url,
                    "recipient_email": user.email,
                },
            )

        except User.DoesNotExist:
            # Don't reveal whether the email exists — just return success
            pass
        except Exception as e:
            print("ForgotPasswordEndpoint error:", e)

        # Always respond the same way to prevent account enumeration
        return Response({
            "message": "If an account with that email exists, a reset link has been sent.",
            "statusCode": 200,
        })


class ResetPasswordEndpoint(APIView):
    """
    Author: [Your Name] on April 18, 2025
    Purpose: Validates the uid + token from the emailed link, then
             updates the user's password to the supplied new_password.
    Input parameters: uid, token, new_password
    Return: { message, statusCode }
    """

    def post(self, request):
        uid = request.data.get("uid", "")
        token = request.data.get("token", "")
        new_password = request.data.get("new_password", "")

        if not uid or not token or not new_password:
            return Response({
                "message": "uid, token, and new_password are all required.",
                "statusCode": 400,
            })

        try:
            # Decode the uid back to a user pk
            user_pk = force_str(urlsafe_base64_decode(uid))
            user = User.objects.get(pk=user_pk)
        except (User.DoesNotExist, ValueError, OverflowError, Exception) as e:
            print("ResetPasswordEndpoint - user lookup error:", e)
            return Response({
                "message": "Invalid or expired reset link.",
                "statusCode": 400,
            })

        # Validate the one-time token
        if not default_token_generator.check_token(user, token):
            return Response({
                "message": "Reset link is invalid or has expired.",
                "statusCode": 400,
            })

        if len(new_password) < 6:
            return Response({
                "message": "Password must be at least 6 characters.",
                "statusCode": 400,
            })

        # All good — set the new password
        user.password = make_password(new_password)
        user.save()

        return Response({
            "message": "Password reset successfully. You can now sign in.",
            "statusCode": 200,
        })
